include_recipe "chef_gem_fix"
include_recipe "docker_custom"

#include_recipe "docker_memcached"
#include_recipe "docker_youtrack"
#include_recipe "docker_rails"
#include_recipe "docker_laravel"
include_recipe "docker_nginx"
include_recipe "after_haproxy"
include_recipe "docker_nginx_cleaner"
